# Generated by Django 3.1.3 on 2021-05-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210528_0322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='pickup',
            new_name='pickup_address',
        ),
    ]
