# Generated by Django 3.1.3 on 2021-05-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210529_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='delivery_photo',
            field=models.ImageField(blank=True, null=True, upload_to='job/delivery_photos/'),
        ),
    ]
